name: uide
description: Uide application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  http: ^0.13.4
  http_parser: ^4.0.2
  image_picker: ^0.8.8
  intl_phone_field: ^3.1.0
  json_annotation: ^4.8.1
  like_button: ^2.0.5
  photo_view: ^0.14.0
  provider: ^6.0.5
  responsive_framework: ^1.0.0
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
